import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Providers from '@/components/Providers'
import Chat from "@/components/Chat";
import { Toaster } from 'sonner';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className="h-full">
      <Providers>
      <body
        className={cn("relative h-full font-sans antialiased")}
      >

        <main className="relative flex flex-col min-h-screen">
          <Navbar />
          <div className="flex-grow flex-1">
          <Chat />

          {children}

          </div>
      <Toaster position="top-right" richColors />
        </main>
      </body>

      </Providers>
    </html>
  );
}
